// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PostManager.Domain.Model;

[Table("Notificacao")]
public partial class Notificacao : BaseEntity
{
    public int UsuarioId { get; set; }

    public int PostId { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("Notificacaos")]
    public virtual Post Post { get; set; }

    [ForeignKey("UsuarioId")]
    [InverseProperty("Notificacaos")]
    public virtual Usuario Usuario { get; set; }
}