// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PostManager.Domain.Model;

[Table("Post")]
public partial class Post : BaseEntity
{
    [Required]
    [Column(TypeName = "ntext")]
    public string Descricao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    public int UsuarioId { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Notificacao> Notificacaos { get; set; } = new List<Notificacao>();

    [ForeignKey("UsuarioId")]
    [InverseProperty("Posts")]
    public virtual Usuario Usuario { get; set; }
}