// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PostManager.Domain.Model;

[Table("Usuario")]
public partial class Usuario : BaseEntity
{
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Senha { get; set; }
    [NotMapped]
    public string ConfirmSenha { get; set; }
    [NotMapped]
    public string NovaSenha { get; set; }
    [NotMapped]
    public string ConfirmNovaSenha { get; set; }

    [InverseProperty("Usuario")]
    public virtual ICollection<Notificacao> Notificacaos { get; set; } = new List<Notificacao>();

    [InverseProperty("Usuario")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}