// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace PostManager.API.DTO;

public partial class UsuarioDTO
{
    public int Id { get; set; }

    public string Nome { get; set; }
    public string Email { get; set; }

    public string Senha { get; set; }
    public string ConfirmSenha { get; set; }

    public string NovaSenha { get; set; }
    public string ConfirmNovaSenha { get; set; }
    public virtual ICollection<PostDTO> Posts { get; set; } = new List<PostDTO>();
}